version: '3'
services:
 ghost:
  image: ghost:1-alpine
  restart: always
  ports:
    - 2368:2368
  environment:
    database__client: mysql
    database__connection__host: mysql
    database__connection__user: ghost
    database__connection__password: password
    database__connection__database: db
  networks:
    - my-network
  depends_on:
    - mysql
 mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: db
    MYSQL_USER: ghost
    MYSQL_PASSWORD: password
  networks:
    - my-network
  volumes:
    - mysql_data:/var/lib/mysql
  

volumes:
  ghost:
  mysql_data:

networks:
  my-network: